modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory (26 is current forge version)
[[mods]] #mandatory
modId="fearmenot" #mandatory
version="1.0" #mandatory
displayName="Fear Me! (not)" #mandatory

[[dependencies.fearmenot]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="SERVER"